name: build-image

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version
        id: version
        run: echo "VERSION=0.0.$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build \
            -t gauaslab/upload-service:latest \
            -t gauaslab/upload-service:${{ steps.version.outputs.VERSION }} \
            .
          docker push gauaslab/upload-service:latest
          docker push gauaslab/upload-service:${{ steps.version.outputs.VERSION }}
